### ISSUE TITLE
TLS?

### ISSUE THREAD

**Issue by Term1nal** [sorcix/irc#14]
I found this library, and it looks quite good and solid, but what appeared to be specifically lacking was TLS support. Or at least any reference to it, is connecting via SSL/TLS possible, or would this library need some modifications first?

If so, would the library be open to the additions in the form of  PR? What is the contribution process?

**Comment by MorpheusXAUT** [comment]
Although I'm not 100% sure, you should be able to use TLS connections just fine with this library. The first given example (nickvanw/ircx), which also utilises this library, provides TLS functionality as well, simply using tls.Dial instead of net.Dial when creating the required network connection (to be seen at: https://github.com/nickvanw/ircx/blob/master/bot.go#L51).

I wouldn't see any reason why you could just handle the network dialing (and creation of a TLS connection) yourself and pass the resulting connection object to the library: https://github.com/sorcix/irc/blob/master/stream.go#L31

The built-in Dial function of this library only supports non-TLS connections, but it doesn't do more than call net.Dial and NewConn anyways :smile: Something like DialWithTLS could be added for convenience, but you could easily just "work around" that yourself.

Sorry, @sorcix, I hope you don't mind me posting in here as well :smiley:

**Comment by belak** [comment]
Yes, a `*tls.Conn` should work just fine. I simply use `irc.NewConn` in anything I'm writing which uses this library anyway.

**Comment by sorcix** [comment]
What @MorpheusXAUT said. TLS is outside the scope of this package, but can easily be used with [irc.NewConn](http://godoc.org/github.com/sorcix/irc#NewConn).

**Comment by Term1nal** [comment]
irc.NewConn works for me I suppose, thanks for the feedback!

**Comment by donatj** [comment]
For anyone curious as I was, to get it working I simply replaced I replaced:

```go
	conn, err := irc.Dial(fmt.Sprintf("%s:%d", b.server, b.port))
	if err != nil {
		return err
	}
```

with:

```go
	var t io.ReadWriteCloser
	var err error

	addr := fmt.Sprintf("%s:%d", b.server, b.port)

	if b.ssl {
		t, err = tls.Dial("tcp", addr, &tls.Config{})
	} else {
		t, err = net.Dial("tcp", addr)
	}

	if err != nil {
		return err
	}

	b.conn = irc.NewConn(t)
```

**Comment by sorcix** [comment]
Hmm. This should be added as an example in the godocs.
